auth_token = "_Qk9YLTEKYmxkci0yMDE3MDkyNzAyMzcxNApibGRyLTIwMTcwOTI3MDIzNzE0Cm0wanhRRjFwaUxiekdmaUt3L1RYdG1UVFpNOFh2Q3ExClkxSkkrWEJ3Zml2cjB2eitXNVdVNmd0VVVRemg2alJoRXlLd0NOV1RuaXBuNTdXeQ=="
origin = "core"
bldr_url = "https://bldr.habitat.sh/"
