auth_token = "_Qk9YLTEKYmxkci0yMDIyMDIxNjEwNTc0MQpibGRyLTIwMjIwMjE2MTA1NzQxCnhvSlR4WmlkZXFTN08yLzhZdDJ1SW8yTE52SFZQa3pWCndZcUxYMG5xaS9iWnc2ZEttZ2J3NWl0eVRVVnp4U2ZEdG5uUzFHN05rWUNKeGpBNw=="
origin = "core"
bldr_url = "https://bldr.habitat.sh/"
